### ISSUE TITLE
环境问题

### ISSUE THREAD

**Issue by ghost** [Bobholamovic/CDLab#21]
感谢开源精彩的代码

我在运行train.py时遇到问题如下：
Traceback (most recent call last):
  File "train.py", line 12, in <module>
    import impl.builders
  File "/media/lscsc/nas/yihan/CDlab/CDLab/src/impl/builders/__init__.py", line 1, in <module>
    from .critn_builders import *
  File "/media/lscsc/nas/yihan/CDlab/CDLab/src/impl/builders/critn_builders.py", line 7, in <module>
    from core.misc import CRITNS
ModuleNotFoundError: No module named 'core.misc'

请问如何获得core.misc模块

**Comment by Bobholamovic** [comment]
请问本地有`core`目录存在嘛？如果没有的话，可能是git clone的时候没有指定`--recursive`，所以没有把submodule一起下载下来

**Comment by ghost** [comment]
多谢提醒 👍
