### ISSUE TITLE
代码复现Train.py的问题

### ISSUE THREAD

**Issue by XiaoJ058** [Bobholamovic/CDLab#27]
大佬您好，我是刚入门深度学习的小白。我想不在终端运行您的代码，于是我在train.py中run，但是报错：
Traceback (most recent call last):
  File "F:\pycharm\pycharm2021\PyCharm 2021.3\plugins\python\helpers\pydev\pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "F:\pycharm\pycharm2021\PyCharm 2021.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/dl_file/py_file/train_code/classic_model/CDLab/src/train.py", line 79, in <module>
    main()
  File "E:/dl_file/py_file/train_code/classic_model/CDLab/src/train.py", line 57, in main
    trainer = R['Trainer_switcher'](args)
  File "E:\dl_file\py_file\train_code\classic_model\CDLab\src\core\trainer.py", line 241, in __call__
    print(p(args))
  File "E:\dl_file\py_file\train_code\classic_model\CDLab\src\impl\trainers\__init__.py", line 17, in <lambda>
    trainer_switcher.add_item(lambda C: C['model']=='DSAMNet', DSAMNetTrainer)
TypeError: 'Namespace' object is not subscriptable

Process finished with exit code 1
关于这方面的知识，想跟您请教一下，方便的话可以加您学习一下嘛？
关于您论文中的时间维度创新点，我觉得非常有意思，在我的模型中也有借鉴参考，对您做的工作非常感谢！

**Comment by Bobholamovic** [comment]
你好，有可能需要在PyCharm设置一些命令行参数，可以参考这里：https://blog.csdn.net/counte_rking/article/details/78837028

**Comment by XiaoJ058** [comment]
好的，非常感谢
