### ISSUE TITLE
大佬您好，我是一个刚接触深度学习的小白，在运行您的代码train.py时遇到问题

### ISSUE THREAD

**Issue by zyh-pretty** [Bobholamovic/CDLab#35]
Traceback (most recent call last):   File "E:\data\CDLab\CDLab\src\train.py", line 73, in <module>     main()   File "E:\data\CDLab\CDLab\src\train.py", line 51, in main     trainer = R['Trainer_switcher'](args)   File "E:\data\CDLab\CDLab\src\core\trainer.py", line 242, in __call__     return t(args) if return_obj else t   File "E:\data\CDLab\CDLab\src\impl\trainers\cd_trainer.py", line 24, in __init__     super().__init__(settings['model'], settings['dataset'], settings['criterion'], settings['optimizer'], settings)   File "E:\data\CDLab\CDLab\src\core\trainer.py", line 27, in __init__     self.gpc = OutPathGetter(   File "E:\data\CDLab\CDLab\src\core\misc.py", line 287, in __init__     self.update_vfs(False)   File "E:\data\CDLab\CDLab\src\core\misc.py", line 312, in update_vfs     self._dir_tree.perform(lambda x: self.make_dir(x.path))   File "E:\data\CDLab\CDLab\src\core\misc.py", line 219, in perform     return self.root.apply(func)   File "E:\data\CDLab\CDLab\src\core\misc.py", line 162, in apply     ret = [func(self)]   File "E:\data\CDLab\CDLab\src\core\misc.py", line 312, in <lambda>     self._dir_tree.perform(lambda x: self.make_dir(x.path))   File "E:\data\CDLab\CDLab\src\core\misc.py", line 326, in make_dir     os.mkdir(path) FileNotFoundError: [WinError 3] 系统找不到指定的路径。: '../exp/levircd'   请大佬指教，多谢！！！

**Comment by Bobholamovic** [comment]
请问脚本是在`src`目录执行的吗？如果使用相对路径`../exp/levircd`的话，需要确保运行脚本时的工作目录在`src`～

**Comment by zyh-pretty** [comment]
是在的，但是exp里没有levircd文件夹，我又创建了一个，运行还是不可以

**Comment by zyh-pretty** [comment]
相对路径../exp/levircd具体在哪个代码里呀，我没有找到。。

**Comment by Bobholamovic** [comment]
理论上应该是会自动创建的，我不确定是不是Windows系统路径的问题，可以试试用绝对路径～

**Comment by zyh-pretty** [comment]
../exp/levircd配置这个的代码在哪个文件里呀大佬，我找了好久没找到

**Comment by Bobholamovic** [comment]
这个一般是在执行指令的时候自己指定的参数。比如你执行的指令可能是：`python train.py train --exp_config ../exp/levircd`。

**Comment by zyh-pretty** [comment]
我的运行指令是python E:\data\CDLab\CDLab\src\train.py train --exp_config E:\data\CDLab\CDLab\configs\levircd\config_levircd.yaml，并没有../exp/levircd

**Comment by Bobholamovic** [comment]
> 我的运行指令是python E:\data\CDLab\CDLab\src\train.py train --exp_config E:\data\CDLab\CDLab\configs\levircd\config_levircd.yaml，并没有../exp/levircd

可能需要指定具体的模型，比如`config_levircd_cdnet.yaml`。

**Comment by adleess** [comment]
> Traceback (most recent call last): File "E:\data\CDLab\CDLab\src\train.py", line 73, in main() File "E:\data\CDLab\CDLab\src\train.py", line 51, in main trainer = R['Trainer_switcher'](args) File "E:\data\CDLab\CDLab\src\core\trainer.py", line 242, in **call** return t(args) if return_obj else t File "E:\data\CDLab\CDLab\src\impl\trainers\cd_trainer.py", line 24, in **init** super().**init**(settings['model'], settings['dataset'], settings['criterion'], settings['optimizer'], settings) File "E:\data\CDLab\CDLab\src\core\trainer.py", line 27, in **init** self.gpc = OutPathGetter( File "E:\data\CDLab\CDLab\src\core\misc.py", line 287, in **init** self.update_vfs(False) File "E:\data\CDLab\CDLab\src\core\misc.py", line 312, in update_vfs self._dir_tree.perform(lambda x: self.make_dir(x.path)) File "E:\data\CDLab\CDLab\src\core\misc.py", line 219, in perform return self.root.apply(func) File "E:\data\CDLab\CDLab\src\core\misc.py", line 162, in apply ret = [func(self)] File "E:\data\CDLab\CDLab\src\core\misc.py", line 312, in self._dir_tree.perform(lambda x: self.make_dir(x.path)) File "E:\data\CDLab\CDLab\src\core\misc.py", line 326, in make_dir os.mkdir(path) FileNotFoundError: [WinError 3] 系统找不到指定的路径。: '../exp/levircd' 请大佬指教，多谢！！！

兄弟你解决了吗，我直接在window下跑也是这个错
