### ISSUE TITLE
你好，我是一个初学者，想问一下出现这个问题是什么原因，如何修改呢

### ISSUE THREAD

**Issue by 121zzy** [Bobholamovic/CDLab#38]
Traceback (most recent call last):
  File "train.py", line 75, in <module>
    main()
  File "train.py", line 53, in main
    trainer = R['Trainer_switcher'](args)
KeyError: 'Trainer_switcher'

**Comment by Bobholamovic** [comment]
你好，通过上述报错信息不太容易确定问题的原因。请确认你没有对代码做过改动～ 另外建议在报错的第53行之前`print(R.keys())`查看注册的组件类型是否符合预期。
